---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  
  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: In-Memory inventory playbook
  hosts: localhost
  gather_facts: false
  #workstation-8d8b.blue.osp.opentlc.com
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: openstack
      register: result
    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{ result.ansible_facts.openstack_servers }}"
    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{ result.ansible_facts.openstack_servers }}"

#Work via roles

- name: setup tomcat and postgres
  hosts: apps,appdbs
  roles:
    - rnelle.tomcat
    - rnelle.postgres

- name: setup haproxy
  hosts: frontends
  roles: 
    - rnelle.haproxy
    
#Remaining tasks not used in roles

- name: deploy apache
  gather_facts: false
  become: true
  hosts: apps
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: enable apache at boot
    service:
      name: httpd
      enabled: yes
  - name: start apache
    service:
      name: httpd
      state: started
